repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: '^brian2/_version.py$'
        files: '^brian2/.*\.pyi?$'
  - repo: https://github.com/psf/black
    rev: '22.10.0'
    hooks:
      - id: black
        exclude: '^brian2/_version.py$'
        files: '^brian2/.*\.pyi?$'
