[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython",
    "oldest-supported-numpy",
    "versioneer[toml]",
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py38']
include = '^/brian2/.*\.pyi?$'
extend-exclude = '^/brian2/_version.py$'
preview = true

[tool.isort]
atomic = true
profile = "black"
py_version = "38"
skip_gitignore = true
# NOTE: isort has no "include" option, only "skip".
extend_skip = ["brian2/_version.py"]
skip_glob = ["dev/*", "docs_sphinx/*", "examples/*", "tutorials/*"]

[tool.versioneer]
VCS = 'git'
style = 'pep440-pre'
versionfile_source = 'brian2/_version.py'
versionfile_build = 'brian2/_version.py'
tag_prefix = ''
parentdir_prefix = 'brian2-'

[tool.pytest.ini_options]
markers = [
    "codegen_independent: tests that do not generate/compile code",
    "standalone_compatible: tests that can be run in standalone mode",
    "multiple_runs: tests containing multiple run statements",
    "cpp_standalone: tests specifically for C++ standalone mode",
    "standalone_only: tests that should only run in standalone mode",
    "openmp: tests that run multi-threaded simulations with OpenMP",
    "gsl: tests that require the Gnu Scienfitic Library",
    "long: long running tests",
]