[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython",
    "oldest-supported-numpy",
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py37']
include = '^/brian2/.*\.pyi?$'
extend-exclude = '^/brian2/_version.py$'
preview = true
